name: 'Check Licenses'
description: 'Detect new dependencies in a PR and add reminder comments to review licensing details'
inputs:
  dependency-file:
    description: 'Path to a package.json/requirements.txt file'
    required: true
  message-file:
    description: 'Path to markdown message mustache template'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
